/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideCategoryRouteImport } from './routes/guide.$category'
import { Route as BankBankIdRouteImport } from './routes/bank.$bankId'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideCategoryRoute = GuideCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => GuideRoute,
} as any)
const BankBankIdRoute = BankBankIdRouteImport.update({
  id: '/bank/$bankId',
  path: '/bank/$bankId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/compare': typeof CompareRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/simulator': typeof SimulatorRoute
  '/bank/$bankId': typeof BankBankIdRoute
  '/guide/$category': typeof GuideCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/compare': typeof CompareRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/simulator': typeof SimulatorRoute
  '/bank/$bankId': typeof BankBankIdRoute
  '/guide/$category': typeof GuideCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/compare': typeof CompareRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/simulator': typeof SimulatorRoute
  '/bank/$bankId': typeof BankBankIdRoute
  '/guide/$category': typeof GuideCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/compare'
    | '/documents'
    | '/guide'
    | '/onboarding'
    | '/simulator'
    | '/bank/$bankId'
    | '/guide/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/compare'
    | '/documents'
    | '/guide'
    | '/onboarding'
    | '/simulator'
    | '/bank/$bankId'
    | '/guide/$category'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/compare'
    | '/documents'
    | '/guide'
    | '/onboarding'
    | '/simulator'
    | '/bank/$bankId'
    | '/guide/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  CompareRoute: typeof CompareRoute
  DocumentsRoute: typeof DocumentsRoute
  GuideRoute: typeof GuideRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SimulatorRoute: typeof SimulatorRoute
  BankBankIdRoute: typeof BankBankIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$category': {
      id: '/guide/$category'
      path: '/$category'
      fullPath: '/guide/$category'
      preLoaderRoute: typeof GuideCategoryRouteImport
      parentRoute: typeof GuideRoute
    }
    '/bank/$bankId': {
      id: '/bank/$bankId'
      path: '/bank/$bankId'
      fullPath: '/bank/$bankId'
      preLoaderRoute: typeof BankBankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuideRouteChildren {
  GuideCategoryRoute: typeof GuideCategoryRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideCategoryRoute: GuideCategoryRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  CompareRoute: CompareRoute,
  DocumentsRoute: DocumentsRoute,
  GuideRoute: GuideRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SimulatorRoute: SimulatorRoute,
  BankBankIdRoute: BankBankIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
